### ISSUE TITLE
Too few active voxel Error and memory-resolution tradeoff problem

### ISSUE THREAD

**Issue by ariel415el** [PKU-YuanGroup/UltraShape-1.0#12]
Hey thank you for releasing the code for this great work!

running infer_dit_refine.py ok for most input coarse meshes.
However, for some meshes I'm getting this error:

> RuntimeError: The size of tensor a (32769) must match the size of tensor b (17429) at non-singleton dimension 2

Judging by this print I'm getting
> [Info] Voxel count (17428) < Target (32768). Sampling 17428 points.

And looking at the code here 
https://github.com/PKU-YuanGroup/UltraShape-1.0/blob/406ba76d02b2d6ae63bee4f898f3cae2131712ea/ultrashape/utils/voxelize.py#L14

It seem like the coarse mesh I got from Hnyuan3d-2.1 has too few active active voxels in it (17428) while 32768 are required.

I thought about increasing the resolution to increase the number of unique active voxels and changed 
https://github.com/PKU-YuanGroup/UltraShape-1.0/blob/406ba76d02b2d6ae63bee4f898f3cae2131712ea/configs/infer_dit_refine.yaml#L29
from 128 to 256 but i'm getting OOM even in a 80Gb gpu machine

Is all of this expected?  how can i reduce memory footprint and run with higher resolution?
Any other solution

**Comment by ariel415el** [comment]
Also, it seems that the volume decoding code does not use batching in the second loop (only in the first)
https://github.com/PKU-YuanGroup/UltraShape-1.0/blob/406ba76d02b2d6ae63bee4f898f3cae2131712ea/ultrashape/models/autoencoders/volume_decoders.py#L408-L419

The number of queries (sum_num) here is huge >200k and exceeds memory

**Comment by jclarkk** [comment]
Hey @ariel415el 
I've posted this on a different issue, but it's relevant here too. I've managed to do memory optimizations that allow running UltraShape with much less VRAM on my fork:
https://github.com/jclarkk/UltraShape-1.0

**Comment by StarRealMan** [comment]
Thanks for reporting this issue! 🙏 @ariel415el @jclarkk 
If you have a fix, feel free to open a Pull Request — we’d be happy to merge it.
Thanks again for your contribution!

**Comment by jclarkk** [comment]
@siraxe 
I'm not one of the official maintainers/creators of this repository, so you'll have to ask them if there is a workaround for this dependency.

In any case, I'll always recommend using WSL2 in Windows instead of running a Python interpreter directly on Windows.

**Comment by jclarkk** [comment]
@siraxe 
Make sure you're using the recommended amount of num_latents and chunk_size. In the PR I've kept their values as default so we won't harm the quality, but you can now control their values.

**Comment by thj2333** [comment]
@ariel415el 
Since the model was trained with voxel_query_res = 128, running inference at 256 resolution requires first interpolating voxel_cond to the range (0, 128). We have provided a new function, precompute_freqs_cis_3d_interpolated, to support this.

We also want to thank you (@ariel415el) and @jclarkk for your helpful suggestions. Based on your feedback, we fixed an OOM issue that occurred during FlashVDM decoding.

Below is a comparison of the refine results using voxel conditions at 128 and 256 resolutions. The 128 resolution tends to produce richer fine-grained details, while the 256 resolution adheres more strictly to the geometry of the coarse mesh. For the current version, we therefore recommend using the 128 resolution.
<img width="1360" height="894" alt="Image" src="https://github.com/user-attachments/assets/6fe8cb32-4960-4526-a4c1-5cbf5a3daa62" />

**Comment by ariel415el** [comment]
@thj2333 it seems like there is no reason to use higher resolution. Especially when the "too few active voxels" problem was solved in @jclarkk's PR.

Thank you all for the replies.
